services:
  postgres:
    image: postgres:latest
    container_name: postgres-mcp-demo
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      MCP_TEST_USER: ${MCP_TEST_USER:-mcp_user}
      MCP_TEST_PASSWORD: ${MCP_TEST_PASSWORD:-mcp_password}
      MCP_TEST_DB: ${MCP_TEST_DB:-mcp_test}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
